// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxhwkifayptucnkjcpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneGh3a2lmYXlwdHVjbmtqY3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDIxOTMsImV4cCI6MjA2NjYxODE5M30.0YvdTEWwzj_rC-UqPfD3noIDMOXk-vJW9fOUeUl_mZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});